sudo: required
language: android
before_cache:
  - rm -f  $HOME/.gradle/caches/*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
android:
  components:
        - tools
        - tools # Running this twice get's the latest build tools
        - platform-tools
        - android-27
        - build-tools-27.0.3
        - extra
licenses:
  - 'android-sdk-license-.+'
before_install:
  - gem install fir-cli
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;27.0.3"
script:
    - "chmod +x ./gradlew"
    - "./gradlew assembleRelease"

after_deploy:
    - fir p apks/*.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"