language: android
env:
 global:
    - ANDROID_API=27
    - ANDROID_BUILD_TOOLS=27.0.3
    - echo yes | sdkmanager "build-tools;27.0.3"
components:
      - tools
      - tools # Running this twice get's the latest build tools
      - platform-tools
      - android-${ANDROID_API}
      - build-tools-${ANDROID_BUILD_TOOLS}
      - extra
before_cache:
  - rm -f  $HOME/.gradle/caches/*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
    - "chmod +x ./gradlew"
    - "./gradlew assembleRelease"

before_install:
    - gem install fir-cli
after_deploy:
    - fir p apks/*.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"