language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;27.0.3"
components:
      - echo yes | sdkmanager "build-tools;27.0.3"
      - echo yes | sdkmanager "platforms;android-27"
      - tools
      - tools # Running this twice get's the latest build tools
      - platform-tools
      - echo yes | sdkmanager "platforms;android-27"
      - android-27
      - build-tools-27.0.3
      - echo yes | sdkmanager "build-tools;27.0.3"
      - extra
before_cache:
  - rm -f  $HOME/.gradle/caches/*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
    - "chmod +x ./gradlew"
    - "./gradlew assembleRelease"

before_install:
    - gem install fir-cli
after_deploy:
    - fir p apks/*.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"