language: android
components:
    - build-tools-26.0.2
    - android-27
before_cache:
  - rm -f  $HOME/.gradle/caches/*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
    - "chmod +x ./gradlew"
    - "./gradlew assembleRelease"

before_install:
    - gem install fir-cli
after_deploy:
    - fir p apks/*.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"